<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.demodd</groupId>
        <artifactId>demodd-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>application</artifactId>
    <name>application</name>
    <description>Módulo de Aplicación - Casos de uso, orquestación y DTOs (Hexagonal / DDD)</description>

    <dependencies>
        <dependency>
            <groupId>com.demodd</groupId>
            <artifactId>domain</artifactId>
        </dependency>
    </dependencies>
</project>
